name: 01 Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test || true # Continue even if tests fail

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4 # Create a test report inside GitHub
        # Always run, even if tests fail
        if: success() || failure()
        with:
          report_paths: "**/target/surefire-reports/*.xml"

          - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
  
      - name: Install pyxml2pdf
        run: |
          pip install pyxml2pdf

      - name: Convert XML to PDF
        run: |
          # Create input and output directories
          mkdir -p input output

          # Move XML files to input directory
          mv target/surefire-reports/*.xml input/

          # Convert the XML files to PDF
          python -m pyxml2pdf.main input/test-results.xml --pdf output/test-report.pdf

      - name: Upload PDF Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-pdf
