name: 01 Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test || true # Continue even if tests fail

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4 # Create a test report inside GitHub
        # Always run, even if tests fail
        if: success() || failure()
        with:
          report_paths: "**/target/surefire-reports/*.xml"

      - name: Create output directory
        run: mkdir -p target/test-reports

      - name: Install JUnit PDF Report
        run: |
          curl -L -o junit-pdf-report.jar https://github.com/benmoss/junit-pdf-report/releases/latest/download/junit-pdf-report.jar

      - name: Convert XML to PDF using JUnit PDF Report
        run: |
          java -jar junit-pdf-report.jar -o target/test-reports/test-report.pdf target/surefire-reports/*.xml

      - name: Upload PDF Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-pdf
          path: target/test-reports/*.pdf
